import React from "react"
import "./personajes.css"



const Personajes = () => {
    return (
        <div className="contenedorPersonajes">
            <h1>Personajes</h1>
            <h3>Daemon Targaryen</h3> *
            <img className="img1" src="https://st1.uvnimg.com/89/ad/df2e783d460f9790e7b013d7b00f/daemon-targaryen-house-of-the-dragon-serie.jpg" alt="" />
            <p className="house2">  Daemon es nieto de Jaehaerys I Targaryen, hermano menor del rey Viserys y presunto heredero del Trono de Hierro. Ser Otto Hightower, la Mano del Rey, considera a Daemon como un hombre impredecible y una amenaza para el reino. Es el jinete del dragón Caraxesy empuña la espada Hermana Oscura, la espada de acero valyrio de la tía abuela de su abuelo, la reina Visenya Targaryen. A diferencia de su hermano mayor, Daemon es, a pesar de su gran astucia, un canalla impredecible e impulsivo.

                En el Gran Consejo de 101 d.C., Viserys fue elegido por los señores de Poniente como sucesor del rey Jaehaerys, cuya salud había comenzado a fallar y que había perdido a sus dos hijos. Durante los primeros nueve años del reinado de su hermano, Daemon sirvió en el Consejo Privado, tanto como Consejero de Edictos y luego como Consejero de la Moneda. Sin embargo, fue destituido en ambas ocasiones por insistencia de Otto Hightower. La rivalidad entre Daemon y Otto continuó, ya que la Mano vio al príncipe como una amenaza si alguna vez se convertía en rey, posiblemente un segundo Maegor el Cruel. Daemon, a su vez, ve a Otto como una sanguijuela deshonrosa que quería ascender lo más alto posible, ya que su condición de segundo hijo no le permitiría heredar nada propio. La mayor parte del Consejo se puso del lado de Otto en este conflicto, pero Daemon siempre fue defendido por su hermano.

                En algún momento, el rey Viserys arregló el matrimonio de su hermano menor, casándolo con Lady Rhea Royce, Señora de Piedra de las Runas. Ninguna de las partes estaba contenta con el matrimonio, y Daemon se refiriere despectivamente a su esposa como su "zorra de bronce".

                El escudo de armas personal de Daemon presenta el dragón rojo de tres cabezas de la Casa Targaryen, adornado con escamas doradas y dentro de un borde de fuego dorado. Su casco, forjado en acero valyrio, está adornado con la cabeza y las alas de un dragón.</p>

            <h3>Rhaenyra targaryen</h3>
            <img className="img1" src="https://vader.news/__export/1667053567195/sites/gadgets/img/2022/10/29/rhaenyra-in-house-of-the-dragon.jpg_1201130903.jpg" alt="" />
            <p className="house2" >Nacida en 97 d.C., la princesa Rhaenyra fue la única hija superviviente del entonces príncipe Viserys Targaryen y su prima, Lady Aemma Arryn. Tuvo un hermano mayor que murió durante la infancia.Rhaenyra se convirtió en jinete de dragón a la edad de siete años, ligada al dragón Syrax. Un año después, a los ocho años, Rhaenyra se convirtió en copera de su padre, sirviéndo en su mesa, en los torneos y en la corte. Desde ese momento en adelante, al rey Viserys I rara vez se le veía sin Rhaenyra.A edad temprana, Rhaenyra se encaprichó de su tío, el príncipe Daemon Targaryen, quien a menudo iba de viaje al otro lado del Mar Angosto y le traía regalos exóticos. Durante el torneo de Poza de la Doncella celebrado por la coronación del rey Viserys I, Ser Criston Cole ganó el combate cuerpo a cuerpo, derrotando al príncipe Daemon. Ser Criston coronó a Rhaenyra como Reina del Amor y la Belleza, después de lo cual pidió su favor para lucir en la justa. En 105 d.C., Ser Criston Cole fue nombrado hermano juramentado de la Guardia Real y Rhaenyra quedó prendada de él, llamandolo "mi caballero blanco". Cuando Rhaenyra suplicó a su padre que nombrara a Cole su escudo y protector personal, Viserys estuvo de acuerdo. A partir de ese momento, Cole siempre llevaría el favor de Rhaenyra en las lizas, y sería su protector durante los eventos públicos.A finales de 105 d.C. su madre, la reina Aemma, murió dando a luz al príncipe Baelon, quien murió al día siguiente; el rey Viserys I y la corte se sumergieron en profundo luto. Para zanjar el asunto de la sucesión y pasando por alto los antecedentes dejados por la decisión del rey Jaehaerys I en 92 d.C. y el Gran Consejo de 101 d.C., el rey Viserys I declaró a Rhaenyra como su legítima heredera, proclamándola Princesa de Rocadragón. En una fastuosa ceremonia en Desembarco del Rey, cientos de señores juraron lealtad a Rhaenyra, prometiendo honrar y defender su derecho de sucesión.En 106 d.C., su padre se casó de nuevo, esta vez con Lady Alicent Hightower, hija de la Mano del Rey Otto Hightower.[8] Madrastra e hijastra se llevaron bien al inicio, pero la situación fue cambiando a mal cuando Alicent dio a luz a sus hijos varones, Aegon en 107 d.C. y Aemond en 110 d.C.. El tema de la sucesión se volvió recurrente en la corte, pero el rey no estaba dispuesto a hablar de ello. Rhaenyra permaneció como su heredera, decisión que Viserys I dejó por escrito en su testamento. Ser Otto Hightower, el padre de la nueva reina y Mano del Rey, fue expulsado de la corte por su insistencia sobre el tema. Aun tras su expulsión, los nobles siguieron mostrando su apoyo a la reina o a la princesa, en dos bandos diferenciados.</p>

            <h3>Viserys I Targaryen</h3>
            <img className="img1" src="https://media.revistagq.com/photos/63452ea6bde63c1026d9cda3/3:2/w_1050,h_700,c_limit/viserys-i-casa-del-dragon-mejor-rey.jpeg" alt="" />
            <p className="house2" >Nacido en 77 d.C. en Desembarco del Rey, el príncipe Viserys fue el hijo mayor del príncipe Baelon Targaryen y su hermana esposa, la princesa Alyssa Targaryen. Tuvo dos hermanos menores, Daemon y Aegon.

                En 92 d.C., el rey Jaehaerys I Targaryen nombró al padre de Viserys como heredero al Trono de Hierro. Sin embargo, el príncipe Baelon murió en 101 d.C., desatando un problema dinástico sobre quién sería el próximo heredero al trono. El rey Jaehaerys I resolvió convocar un Gran Consejo en el que quedaron finalmente dos contendientes por el trono: Laenor Velaryon, hijo de su prima Rhaenys, y Viserys. A pesar de ambos tener un reclamo fuerte, Viserys fue nombrado sucesor de su abuelo.

                Se convirtió brevemente en el último jinete del dragón Balerion, el cual murió de avanzada edad durante el reinado del Viejo Rey.  A la muerte del rey Jaehaerys I en 103 d.C., Viserys fue coronado Rey de los Siete Reinos. Con veintiséis años, el nuevo rey Viserys había estado casado durante una década con su prima, Lady Aemma Arryn. Al año siguiente, un torneo fue celebrado en Poza de la Doncella en honor de su ascenso.El rey Viserys fue conocido como un buen gobernante que siguió la obra de su abuelo Jaehaerys I. Heredó un trono seguro, arcas reales llenas y un legado de paz próspera; la Casa Targaryen llegó al apogeo de su poder durante su reinado. Nunca desde la Maldición de Valyria habían existido tantos príncipes y princesas de la sangre del dragón y Poniente nunca habían tenido tantos dragones.Rodeado de una espléndida corte, el Joven Rey estaba decidido a mantener la paz y la buena voluntad de su abuelo Jaehaerys el Sabio. Junto a la reina Aemma Arryn había tenido un hijo, que murió en la infancia, y una hija, la princesa Rhaenyra, que tenía seis años cuando su padre se convirtió en rey. La princesa se convirtió en su copera real a la edad de ocho años y siempre estuvo al lado de su padre en fiestas, bailes y torneos; la pequeña princesa fue apodada "la delicia del reino".</p>

            <h3>Aemond Targaryen</h3>
            <img className="img1" src="https://fotografias.antena3.com/clipping/cmsimages01/2022/10/14/D46531B7-1D4F-4863-A0B2-1AF7A2E023AF/aemond-casa-dragon_98.jpg?crop=995,560,x0,y0&width=1900&height=1069&optimize=high&format=webply" alt="" />
            <p className="house2">Nacido en 110 d.C., el príncipe Aemond fue el segundo hijo y tercer vástago del rey Viserys I Targaryen y su    segunda esposa, la reina Alicent Hightower. Cuando nació, se dijo que el príncipe Aemond era la mitad del tamaño de su hermano Aegon, pero doblemente feroz.[7]

                Los nacimientos de Aemond y su hermano mayor fueron la causa de algunos conflictos en la corte de Viserys I. El rey había nombrado a Rhaenyra, su única hija superviviente de su primer matrimonio, como heredera oficial en 105 d.C., pero se negó a alterar el orden de la sucesión aunque su segunda esposa le dio hijos varones. Esto finalmente condujo al surgimiento de dos bandos contrarios dentro de la corte, los Verdes (partidarios de la reina Alicent y sus hijos) y los Negros (partidarios de la princesa Rhaenyra). Además, se decía que el príncipe Daemon Targaryen, el hermano menor del rey Viserys y el tío de Aemond, era notablemente frío con Aemond y Aegon, ya que sus nacimientos lo habían hecho descender aún más en la línea de sucesión.

                La enemistad entre la madre de Aemond, Alicent, y su media hermana mayor, Rhaenyra, pasó también a sus hijos. Aemond y sus hermanos se convirtieron en rivales acérrimos de los tres hijos de Rhaenyra, los príncipes Jacaerys, Lucerys y Joffrey Velaryon, resentidos con ellos por robarles su derecho de nacimiento, el Trono de Hierro. El tiempo que los seis muchachos se vieron obligados a pasar juntos (por ejemplo, asistiendo a festines, entrenando juntos en las armas o estudiando con el mismo maestre) solo provocó que aumentara tal aversión.espués del funeral de Ser Laenor Velaryon, el rey Viserys I planeaba visitar Rocadragón para ver si Aemond era "lo suficientemente valiente" para reclamar un huevo de dragón por su propia cuenta. Tratando de demostrar su audacia, a los diez años de edad, Aemond resolvió reclamar al dragón más viejo y más feroz en el mundo conocido, Vhagar, recientemente sin jinete desde la muerte de Laena Velaryon. Al descubrir que su sobrino de tres años Joffrey le estaba espiando, le propinó varias bofetadas y lo empujó a una montaña de excremento de dragón, escapando a lomos de Vhagar. Al volver a tierra, se encontró con que Joffrey y sus hermanos le estaban esperando. Luchó contra ellos y perdió su ojo derecho cuando Luke se lo sacó con su daga. A pesar de la pérdida de su ojo, el príncipe Aemond se convirtió en un guerrero peligroso bajo la tutela de Ser Criston Cole, el Lord Comandante de la Guardia Real.

                Montó el dragón Vhagar durante la Danza de los Dragones, tomando el bando de su hermano Aegon II. Así como el anterior Señor de Bastión de Tormentas, Lord Boremund Baratheon, había sido un partidario de la princesa Rhaenys Targaryen, los Verdes temían que Lord Borros Baratheon, el actual Señor, podría mantenerse en el mismo bando. Por lo tanto, poco después de la muerte de Viserys I, Aemond fue enviado a Bastión de Tormentas, para convencer a Lord Borros de apoyar a Aegon II con la promesa de casarse con una de sus hijas.</p>

            <h3>Aegon II Targaryen </h3>
            <img className="img1" src="https://elcomercio.pe/resizer/GIn6gLDF2Z6eFtBTbBYbkII5dSU=/620x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/Q2AHVUOGAVH5LMKHQ5V5JDEXZE.jpg" alt="" />
            <p className="house2">Nacido en 107 d.C., el príncipe Aegon fue el primer hijo del rey Viserys I Targaryen y su segunda esposa, la reina Alicent Hightower, hija de la Mano del Rey Otto Hightower. Fue nombrado por su madre en honor a Aegon el Conquistador. Tras su nacimiento, el rey Viserys I se negó a realizar cambios en su sucesión, manteniendo a su primogénita, Rhaenyra, como su heredera, una decisión que dejó en su testamento. El príncipe Daemon Targaryen, el hermano menor del rey, se mostraba notablemente frío tanto con Aegon como con Aemond, ya que sus nacimientos habían degradado más a Daemon en la línea de sucesión.

                Cuando fracasaron los intentos de persuadir al rey para que renombra a Aegon como su heredero, Alicent intentó convencer a su esposo de que Rhaenyra y Aegon se casaran. Viserys I no estuvo de acuerdo, ya que los dos hermanos se llevaban diez años de diferencia y no tenían buena relación. El rey Viserys sabía que Alicent solo había propuesto el matrimonio para que Aegon tomara al trono y, por lo tanto, casó a Rhaenyra con Ser Laenor Velaryon en su lugar.

                Tensiones en la corte
                Con los años, la tensión en la corte real aumentó, con los señores nobles tomando partido sobre la sucesión, apoyando a la princesa Rhaenyra o a la reina Alicent. La enemistad entre ambas, pasó también a sus hijos. Aegon y sus hermanos se convirtieron en rivales acérrimos de los tres hijos de Rhaenyra, los príncipes Jacaerys, Lucerys y Joffrey Velaryon, resentidos con ellos por robarles su derecho de nacimiento, el Trono de Hierro. El tiempo que los seis muchachos se vieron obligados a pasar juntos (por ejemplo, asistiendo a festines, entrenando juntos en las armas o estudiando con el mismo maestre) solo provocó que aumentara tal aversión. Aegon estaba convencido de que los hijos de su medio-hermana Rhaenyra habían sido engendrados por de Ser Harwin Strong.

                A los trece años, el príncipe Aegon se había convertido en un jinete del dragón Fuegosol.

                El bando de su madre Alicent Hightower era conocido como "los Verdes", mientras que los partidarios de su medio hermana Rhaenyra eran llamados "los Negros", a raíz del color que la reina y la princesa llevaron en sus vestimentas durante un torneo celebrado en Desembarco del Rey en 111 d.C.

                En 120 d.C., su medio hermana Rhaenyra dio a luz a un hijo al que llamó también Aegon; la reina Alicent lo interpretó como una afrenta y desde entonces fueron conocidos como Aegon el Mayor y Aegon el Menor.

                En 122 d.C., a los quince años, contrajo matrimonio con su hermana, la entonces princesa Helaena Targaryen. Un año después, Helaena dio a luz a los mellizos Jaehaerys y Jaehaera. En 127 d.C. nació su hijo menor, Maelor. Ese mismo año, el príncipe Jacaerys Velaryon pidió a la princesa Helaena bailar con él, Aegon se ofendió. Discutieron, e incluso pudieron llegar a las manos, aunque la Guardia Real no llegó a intervenir.Tras la muerte del monarca en 129 d.C., la reina Alicent Hightower y el Lord Comandante de la Guardia Real, Ser Criston Cole, desafiaron su testamento y conspiraron para coronar a Aegon, aprovechando que Rhaenyra se encontraba en Rocadragón por el nacimiento de su sexto hijo. Cuando llegó la noticia de la muerte de su padre, Aegon no se encontraba con su esposa e hijos, sino en la cama de su amante. En un principio Aegon se negó, pues no quería robar los derechos de su hermana, pero Ser Criston lo convenció argumentando que debería sentarse en el trono un verdadero Targaryen y no un bastardo. Aegon II fue coronado Rey de los Ándalos, los Rhoynar y los Primeros Hombres en Pozo Dragón desencadenando la guerra civil conocida como Danza de los Dragones. Con el anciano Septón Supremo en Antigua, le tocó al Septón Eustace ungirlo con los óleos sangrados y bendecirlo.</p>

            <h3>Alicent Hightower</h3>
            <img className="img1" src="https://assets.vogue.in/photos/6343c7065cd72513ce2ad880/16:9/w_1500,h_843,c_limit/Alicent%20Hightower.jpeg" alt="" />
            <p className="house2">En 101 d.C., Alicent llegó a la corte del rey Jaehaerys I Targaryen a los quince años de edad cuando su padre, Ser Otto Hightower, fue nombrado Mano del Rey. Alicent se convertiría en la compañera constante del Viejo Rey, cuya salud estaba fallando; llevaba la comida al rey, ayudaba a lavarlo y vestirlo, y leía para él. Durante esos años y ya cerca del final de su vida, el rey Jaehaerys a veces la confundía con su hija Saera. Finalmente, el rey Jaehaerys I murió en 103 d.C., mientras Alicent le leía.

                Alicent permaneció en la corte ya que su padre siguió ocupando el cargo de Mano del Rey bajo el reinado del sucesor Jaehaerys, el rey Viserys I Targaryen. Ya desde comienzos del reinado de Viserys, Ser Otto y el príncipe Daemon Targaryen disentían en casi toda opinión; el bufón de la corte, Hongo, afirmaba que la pelea entre los dos hombres comenzó cuando Daemon desfloró a Alicent, pero se desconoce si esto realmente sucedió.En los años que siguieron, Alicent llamó la atención del rey Viserys I, cuya primera esposa, la reina Aemma Arryn, había muerto en 105 d.C.. Los consejeros del rey le instaban a casarse de nuevo y, haciendo caso omiso de todos los consejos, Viserys eligió a Alicent como su nueva esposa. Se casaron en 106 d.C., a pesar de las habladurías de la gente que creía que la Mano del Rey se había elevado muy por encima de lo que realmente valía. Algunas personas incluso dudaban de la virtud de Alicent, ya que los rumores sobre que el príncipe Daemon había tomado su virginidad se habían esparcido; aun más, otros rumores habían aparecido, especialmente aquellos que afirmaban que Alicent dormía con el rey Viserys mientras la reina Aemma estaba aun viva.

                Al comienzo, la reina Alicent tenía una buena relación con su hijastra, la princesa Rhaenyra Targaryen. Pero cuando Alicent dio a luz a un hijo, el príncipe Aegon, una hija, la princesa Helaena, y otro hijo, el príncipe Aemond, en rápida sucesión, y Rhaenyra permaneció heredera del rey Viserys I, esos sentimientos empezaron a cambiar. Ambas mujeres querían ser la primera dama del reino, pero sólo una podía serlo.n 111 d.C., un gran torneo se ofreció en Desembarco del Rey para celebrar el quinto aniversario del matrimonio entre el rey Viserys I y la reina Alicent. En el banquete de bienvenida, la reina vistió una túnica verde, mientras la princesa Rhaenyra usó los colores Targaryen negro y rojo. Luego de esto se volvió costumbre referirse como "los Verdes" y "los Negros" a los partidarios de la reina y de la princesa, respectivamente. Durante el torneo, los negros tuvieron como paladín a Ser Criston Cole quien, llevando la prenda de la princesa Rhaenyra, desmontó a varios campeones de la reina, incluyendo a dos de sus primos y a su hermano menor, Ser Gwayne Hightower.Cuando la princesa Rhaenyra cumplió dieciséis años, el Consejo Privado comenzó a buscar un esposo adecuado para ella. La reina Alicent tenía su propia elección: su hijo mayor, el príncipe Aegon, que era diez años menor que su media hermana. El rey Viserys I se opuso, argumentando que los hermanos nunca se habían llevado bien, pero Alicent instó a su marido que esa era una razón más para casarlos. Viserys se negó, afirmando que Alicent sólo hacía la sugerencia de conseguir que su propia sangre estuviera un día en el trono. Cuando la princesa Rhaenyra se casó con Ser Laenor Velaryon, su antiguo protector de la Guardia Real, Ser Criston Cole, transfirió su lealtad a la reina Alicent. Cole luchó en el torneo de la boda de Rhaenyra con la prenda de la reina Alicent y fue nombrado su protector personal poco después.

                Para 115 d.C. la enemistad entre los Verdes y los Negros había echado raíces profundas. Mientras Alicent había dado a luz al príncipe Daeron, quien, al igual que sus hermanos y hermana tenía los típicos rasgos valyrios de los Targaryen, la princesa Rhaenyra había dado a luz a los príncipes Jacaerys y Lucerys, cuyos rasgos no asemejaban en nada a Rhaenyra o su marido. La reina Alicent estaba convencida de que los niños en realidad habían sido engendrados por Ser Harwin Strong, pero el rey Viserys I no compartía estos sentimientos.

                En 120 d.C. el segundo hijo de Alicent se involucró en un incidente con el hijo de Rhaenyra, Lucerys, que terminó sacándole el ojo derecho a Aemond. Alicent, enfadada, exigió que Lucerys sufriera la pérdida del mismo ojo en castigo. Después de este incidente, el rey Viserys I ordenó que Alicent y sus hijos permanecerían en la corte en Desembarco del Rey, mientras que Rhaenyra y su familia se quedarían en Rocadragón. Más tarde ese mismo año, cuando Rhaenyra dio a luz a su primer hijo con su segundo esposo, el príncipe Daemon Targaryen, Alicent enfureció aun más al enterarse que el niño había sido nombrado Aegon, creyendo que era una ofensa contra su propio primogénito, quien tenía el mismo nombre.

                El primer día del año 127 d.C. el rey Viserys organizó un banquete y obligó a su hija Rhaenyra y a la reina Alicent a asistir con sus respectivos hijos. En un esfuerzo por aplacar al monarca, ambas mujeres obedecieron, luciendo cada una los colores asociados a la otra en señal de amistad. Durante el banquete los príncipes intercambiaron gestos cordiales y compartieron el pan, y el hermano del rey, Daemon, elogió la labor de la Mano del Rey (el padre de Alicent), a lo que este respondió alabando el valor del príncipe. Todos esos gestos sirvieron para alegrar a Viserys, quien, complacido, dio la enemistad entre Negros y Verdes por zanjada.

                Cuando el rey Viserys I murió, al tercer día de la tercera luna en 129 d.C., un sirviente le llevó la noticia a la reina Alicent sin decírselo a nadie. Alicent advirtió a Ser Criston Cole, ahora Lord Comandante de la Guardia Real, y juntos reunieron al Consejo Privado e hicieron planes para coronar al primogénito de Alicent, el príncipe Aegon, en vez de la princesa Rhaenyra. En la ceremonia celebrada en Pozo Dragón, el nuevo rey Aegon II fue coronado; la nueva reina Helaena, hermana y esposa de Aegon, fue coronada por la propia Alicent, quien puso su propia corona sobre la cabeza de su hija y se dirigió a ella como "mi reina"</p>

            <h3>Rhaenys Targaryen</h3>

            <img className="img1" src="https://depor.com/resizer/Dl5oMjLb5905GoApfMeI4TuW-w4=/1200x800/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/S6562DOPTJGV5A3Q7L3PCCZH24.jpg" alt="" />

            <p className="house2">Nacida el séptimo día de la séptima luna de 74 d.C., la princesa Rhaenys fue la única hija del príncipe Aemon Targaryen y Lady Jocelyn Baratheon. De niña era grande y fiera, con el cabello negro de su madre Baratheon y los ojos violeta claro de su padre Targaryen. Como primogénita del Príncipe de Rocadragón, muchos la consideraron la siguiente en la línea de sucesión al Trono de Hierro tras Aemon.Rhaenys se convirtió en jinete de dragón en 87 d.C. cuando reclamó a Meleys. En 89 d.C., la princesa Rhaenys viajó junto a su abuelo, el rey Jaehaerys I Targaryen, en uno de sus viajes reales. Voló en su dragón Meleys hasta Altojardín para reunirse con el rey y juntos visitaron las cuatro Islas Escudo. En Escudo Verde, le informó al rey su intención de desposar a Lord Corlys Velaryon, recibiendo la bendición de su abuelo. La princesa Rhaenys se casó con Lord Corlys en 90 d.C.; ella tenía dieciséis años, el novio treinta y siete. Rhaenys insistió en llegar a la boda a lomos de Meleys. A comienzos de 92 d.C., Rhaenys se enteró de que estaba embarazada de su primer hijo.El padre de Rhaenys, el príncipe Aemon Targaryen, murió en 92 d.C. Como Aemon había sido el Príncipe de Rocadragón, el rey Jaehaerys I debía nombrar formalmente un nuevo heredero al Trono de Hierro. La elección se centró en Rhaenys, la única hija y heredera de Aemon, y el hermano de Aemon, el príncipe Baelon. El rey nombró a Baelon como el nuevo Príncipe de Rocadragón, pasando por alto a la princesa Rhaenys y a su hijo por nacer. La misma Rhaenys fue la primera en objetar la decisión del rey y su esposo, Lord Corlys Velaryon, renunció a su puesto como Lord Almirante y a su lugar en el Consejo Privado. Después de eso, Rhaenys y su esposo regresaron a Marcaderiva. Muchos otros desaprobaron la decisión del rey, incluyeron a la madre de Rhaenys, Lady Jocelyn Baratheon, su tío Lord Boremund Baratheon, y su abuela, la esposa del rey Jaehaerys, la reina Alysanne Targaryen.

                Al año siguiente, Rhaenys dio a luz a su primer hijo, una niña a la que llamó Laena. Un año después, dio a luz a un hijo, Laenor. Aunque tanto la Casa Velaryon como la Casa Baratheon insistieron en que Laenor tenía mayor derecho al trono, el príncipe Baelon siguió siendo el heredero del rey Jaehaerys.

                Cuando el príncipe Baelon murió en 101 d.C., el rey Jaehaerys convocó un Gran Consejo en Harrenhal para decidir el asunto de la sucesión. Se consideraron catorce reclamaciones, incluidas las reclamaciones de Rhaenys y sus hijos. El tío de Rhaenys, Lord Boremund Baratheon, apoyó el reclamo de Rhaenys y su hijo Laenor mientras que Lord Ellard Stark también apoyó a Rhaenys y Corlys. Otros partidarios incluyeron la Casa Dustin de Los Túmulos y la Casa Manderly de Puerto Blanco. Sin embargo, toda muestra de apoyo recayó en Laenor, dejando a Rhaenys y su hija fuera debido a su sexo. Rhaenys y Corlys usaron su riqueza e influencia para persuadir a los señores presentes a votar por su hijo y fueron eventualmente apoyados por Lord Blackwood, Lord Bar Emmon, Lord Celtigar y otros. Sin embargo, Laenor fue finalmente ignorado en favor del hijo mayor de Baelon, el príncipe Viserys.Si bien el recuento se mantuvo en secreto, se rumoreaba que los señores reunidos favorecieron a Viserys por veinte a uno.

                Por haber sido ignorada en la línea de sucesión Hongo, el bufón de la corte, la apodó la reina que nunca fue.

                Después de la muerte de la reina Aemma Arryn en 105 d.C., el Gran Maestre Runciter le sugirió al rey Viserys I Targaryen que desposara a la hija de Rhaenys, Laena, de doce años. El rey Viserys, sin embargo, eligió a Alicent Hightower. Enfurecidos por aquel tercer desprecio de la Casa Targaryen, Rhaenys y su familia no asistieron a la boda en 106 d.C. En 113 d.C., el rey Viserys I y su Consejo Privado comenzaron las discusiones sobre un compromiso para la princesa Rhaenyra Targaryen, la heredera de Viserys. Finalmente acordaron en el hijo de Rhaenys, Laenor. Rhaenyra y Laenor se casaron al año siguiente y tuvieron tres hijos, los príncipes Jacaerys, Lucerys y Joffrey Velaryon.

                No obstante, los dos hijos de Rhaenys murieron en 120 d.C.; Laena murió durante el parto durante los primeros días del año, mientras que Qarl Correy asesinó a Laenor en una feria en Villaespecia.

                Cuando comenzó la Danza de los Dragones en 129 d.C., la princesa Rhaenys fue parte del Consejo Negro de la reina Rhaenyra Targaryen, hija mayor del difunto rey Viserys I Targaryen. Cuando la flota Velaryon cerró el Gaznate, navegando desde Rocadragón y Marcaderiva para bloquear todos los envíos a la bahía del Aguasnegras, el plan de los Negros era que Rhaenys volara con Meleys sobre el bloqueo para evitar que los Verdes atacaran sus barcos con dragones.</p>

                <h3>Lucerys Velaryon</h3>
                <img className="img1" src="https://st1.uvnimg.com/35/52/c22415644aa48578004b4eaa4595/elliot-grihault-es-lucerys-velaryon-en-house-of-the-dragon-hbo.jpg" alt="" />
                <p className="house2">Nacido en 115 d.C. en Rocadragón, el príncipe Lucerys fue el segundo hijo de Ser Laenor Velaryon y la princesa Rhaenyra Targaryen, hija del rey Viserys I y Princesa de Rocadragón. Tuvo dos hermanos, Jacaerys y Joffrey.

Como sus hermanos, Lucerys tenía el cabello y los ojos marrones, en contraste con la apariencia valyria de sus padres. Según el rumor popular, ni Lucerys ni sus hermanos eran hijos legítimos de Ser Laenor, sino que habían sido engendrados por el supuesto amante de la princesa Rhaenyra, Ser Harwin Strong. Sin embargo y por decreto real, cada uno de los hijos de Rhaenyra recibió un huevo de dragón mientras estaba en la cuna. Los que dudaban de la paternidad de los niños susurraban que los huevos nunca eclosionarían, pero el nacimiento de tres dragones demostró lo contrario. La cría de Lucerys recibió el nombre de Arrax.

En 118 d.C., con la bendición del rey Viserys I Targaryen, su madre Rhaenyra anunció el compromiso de Lucerys con su prima Rhaena Targaryen, hija del príncipe Daemon Targaryen y Lady Laena Velaryon.En 120 d.C., cuando Lucerys tenía cinco años, su padre murió. El rey Viserys I, la reina Alicent y sus hijos visitaron Marea Alta en Marcaderiva para el funeral. Al príncipe Aemond, de diez años, le habían dicho que la comitiva iría luego a Rocadragón, para que pudiera reclamar un dragón o un huevo de dragón; el príncipe, sin embargo, estaba decidido a reclamar a Vhagar, el mayor y más grande de los dragones, que recientemente se había quedado sin jinete después de la muerte de Lady Laena Velaryon a principios de ese año. Vhagar estaba presente en Marcaderiva y Aemond, que sabía que sus padres no le permitirían acercarse al dragón, lo intentó en secreto. Sin embargo, fue atrapado por el hermano de tres años de Lucerys, Joffrey. En un intento de mantener al niño callado, lo abofeteó y lo amenazó, antes de empujarlo en una pila de excrementos de dragón. Aemond se subió encima de la espalda de Vhagar y voló dos círculos antes de aterrizar. Cuando aterrizó, encontró a los tres hijos de Rhaenyra esperándolo, pues Joffrey había llamado a sus dos hermanos mayores, Jacaerys y Lucerys. Los cuatro muchachos lucharon con puños y espadas de entrenamiento de madera, hasta que Aemond se burló de sus sobrinos llamándolos "Strong". Jacaerys, lo suficientemente mayor como para comprender el insulto, atacó a Aemond nuevamente. Cuando Aemond ganó la delantera y comenzó a golpear salvajemente a Jacaerys, Lucerys desenvainó su daga y cortó la cara de Aemond, sacando su ojo derecho.

Después del incidente, la reina Alicent exigió que Lucerys perdiera un ojo como penitencia, mientras que la princesa Rhaenyra exigió que Aemond fuera interrogado hasta que revelara dónde había escuchado que sus hijos eran "Strong", sugiriendo que eran bastardos de Harwin Strong y, por lo tanto, implicaba que Rhaenyra era culpable de alta traición. Aemond finalmente admitió haber escuchado la calumnia de su hermano Aegon, quien solo replicó "todos lo saben. Solo mírenlos". El rey Viserys finalmente puso fin al interrogatorio, declarando que ya no escucharía más. Decidió que si alguien se burlaba de sus nietos nuevamente, les arrancarían la lengua con pinzas calientes. Además, Rhaenyra y sus hijos se quedarían en Rocadragón, mientras que Alicent y sus hijos regresaron a Desembarco del Rey.

Ese mismo año, su madre se volvió a casar, esta vez con su tío, el príncipe Daemon Targaryen. Su medio hermano Aegon nació a finales de año, seguido de Viserys en 122 d.C.. A diferencia de Lucerys y sus hermanos, los hijos menores de Rhaenyra tenían la apariencia valyria de los Targaryen.

En 126 d.C., su abuelo, Lord Corlys Velaryon, enfermó. La cuestión de quién lo sucedería como Señor de las Mareas se debatió, ya que sus hijos Laenor y Laena estaban muertos, y el hijo mayor de Laenor, Jacaerys, eventualmente sucedería a su otro abuelo y madre en el Trono de Hierro. Rhaenyra instó a Corlys a nombrar a su segundo hijo, Lucerys, como su heredero; pero el sobrino mayor de Corlys, Ser Vaemond Velaryon, protestó alegando que los hijos mayores de Rhaenyra no eran de Laenor, sino que bastardos de Ser Harwin Strong. Rhaenyra hizo que su esposo le cortara la cabeza a Vaemond, y le dio el cuerpo de comer a su dragón. Los hermanos menores de Vaemond huyeron a Desembarco del Rey con la esposa y los hijos de Vaemond, para pedir justicia ante el rey. El rey Viserys I los escuchó, pero luego ordenó que les arrancaran la lengua, diciéndoles que habían sido advertidos. Mientras descendía del Trono de Hierro, el rey se cortó la mano hasta el hueso con el filo de una espada del trono.Dos años más tarde, en 129 d.C., el rey Viserys I Targaryen murió mientras dormía, lo que desencadenó una guerra civil entre la facción de la reina Rhaenyra Targaryen, reclamando el trono sobre la base de la elección de Viserys, y la facción de su medio hermano el rey Aegon II Targaryen, quien reclamaba el trono por el ser el mayor de los hijos varones de Viserys. En el primer consejo de Aegon en Desembarco del Rey tras la muerte de Viserys, Ser Criston Cole enumeró las razones por las que Rhaenyra no era la heredera legítima, haciendo énfasis en que Jacaerys era un bastardo y que se no podía permitir que un bastardo se sentara en el Trono de Hierro.

El príncipe Lucerys tenía catorce años al inicio de la Danza de los Dragones y había servido por varios años como escudero. Para ese entonces, ya se había convertido en el jinete del dragón Arrax.

Al comienzo de la guerra, fue enviado a Bastión de Tormentas para forjar una alianza con Lord Borros Baratheon, en una misión considerada más corta y más segura que la impuesta a su hermano Jacaerys; en Rocadragón antes de partir, juró a su madre sobre La estrella de siete puntas que no tomaría parte en ningún pleito. Se dirigió al castillo montado en su dragón y allí se encontró con su tío Aemond, el cual también había sido enviado a negociar una alianza. Cuando Lord Borros le preguntó a Luke a cuál de sus cuatro hijas desposaría si firmaba una alianza, Lucerys se vio obligado a admitir que ya estaba comprometido con su prima Rhaena. Tras esto, Lord Borros le dijo que se fuera a casa y aceptó la propuesta de Aemond, pero se negó a asesinar a Lucerys como pedía este último.

Lucerys se marchó de vuelta a Rocadragón sobre Arrax en medio de una gran tormenta. En el camino, fue perseguido por Aemond y su dragón Vhagar; aunque Arrax era más joven y rápido y podría haber salido indemne en un día normal, Vhagar era cinco veces más grande y soportaba mejor los embates de la tormenta. Ambos dragones y sus jinetes se encontraron sobre la Bahía de los Naufragios. Según el Archimaestre Gyldayn, si hubo una pelea no pudo haber durado mucho. Arrax cayó, herido, y fue tragado por las aguas que azotaban la bahía. Su cabeza y cuello fueron enviados a tierra por el mar debajo de los acantilados cercanos a Bastión de Tormentas tres días después</p>

<h3>Jacaerys Velaryon</h3>
<img className="img1" src="https://www.explica.me/__export/1666649298956/sites/debate/img/2022/10/24/sin_txtulo_x1200x750xpxx_x37x_1.png_976912859.png" alt="" />

<p className="house2">Nacido a finales de 114 d.C., el príncipe Jacaerys fue el primer hijo de Ser Laenor Velaryon y la princesa Rhaenyra Targaryen, hija del rey Viserys I y Princesa de Rocadragón. Ser Laenor deseaba nombrar al niño Joffrey, en memoria de su difunto amigo Ser Joffrey Lonmouth, pero su padre, Lord Corlys Velaryon, lo prohibió; en cambio, el niño recibió un nombre tradicional de la Casa Velaryon.

Su tío, el príncipe Daeron Targaryen, hijo del rey Viserys I y la reina Alicent Hightower, nació poco después que Jacaerys. Intentando evitar cualquier enemistad, como la que ya existía entre Rhaenyra y Alicent, Viserys ordenó que Jacaerys y Daeron compartieran una nodriza hasta que fueran destetados, con la esperanza de que ser hermanos de leche creara cercanía entre los niños. Desafortunadamente, las esperanzas del rey de paz entre sus hijos y nietos fueron inútiles. Los tres hijos de Alicent, Aegon, Aemond y Daeron, se convirtieron en acérrimos rivales de los tres hijos de Rhaenyra, resentidos por lo que ellos sentían era el robo de su derecho de nacimiento, el Trono de Hierro. La cercanía forzada entre los seis niños, asistiendo a fiestas, a veces entrenando juntos en armas o estudiando bajo los mismos maestres, solo aumentó esta aversión.

Tuvo dos hermanos menores, Lucerys nacido en 115 d.C., y Joffrey, en 117 d.C. Como sus hermanos, Jacaerys tenía el cabello y los ojos marrones, en contraste con la apariencia valyria de sus padres.Según el rumor popular, ni Jacaerys ni sus hermanos eran hijos legítimos de Ser Laenor, sino que habían sido engendrados por el supuesto amante de la princesa Rhaenyra, Ser Harwin Strong. Sin embargo y por decreto real, cada uno de los hijos de Rhaenyra recibió un huevo de dragón mientras estaba en la cuna. Los que dudaban de la paternidad de los niños susurraban que los huevos nunca eclosionarían, pero el nacimiento de tres dragones demostró lo contrario. La cría de Jacaerys recibió el nombre de Vermax. Según el septón Eustace, el rey Viserys sentó a Jacaerys sobre sus rodillas mientras estaba sentado en el Trono de Hierro y se le escuchó decir "algún día este será tu asiento, muchacho".

En 118 d.C., con la bendición del rey Viserys I Targaryen, su madre anunció el compromiso de Jacaerys con su prima Baela Targaryen, hija del príncipe Daemon Targaryen y Lady Laena Velaryon.Después del incidente, la reina Alicent exigió que Lucerys perdiera un ojo como penitencia, mientras que la princesa Rhaenyra exigió que Aemond fuera interrogado hasta que revelara dónde había escuchado que sus hijos eran "Strong", sugiriendo que eran bastardos de Harwin Strong y, por lo tanto, implicaba que Rhaenyra era culpable de alta traición. Aemond finalmente admitió haber escuchado la calumnia de su hermano Aegon, quien solo replicó "todos lo saben. Solo mírenlos". El rey Viserys finalmente puso fin al interrogatorio, declarando que ya no escucharía más. Decidió que si alguien se burlaba de sus nietos nuevamente, les arrancarían la lengua con pinzas calientes. Además, Rhaenyra y sus hijos se quedarían en Rocadragón, mientras que Alicent y sus hijos regresaron a Desembarco del Rey.

Años más tarde, en 129 d.C., el rey Viserys I Targaryen murió mientras dormía, lo que desencadenó una guerra civil entre la facción de la reina Rhaenyra Targaryen, reclamando el trono sobre la base de la elección de Viserys, y la facción de su medio hermano el rey Aegon II Targaryen, quien reclamaba el trono por el ser el mayor de los hijos varones de Viserys. En el primer consejo de Aegon en Desembarco del Rey tras la muerte de Viserys, Ser Criston Cole enumeró las razones por las que Rhaenyra no era la heredera legítima, haciendo énfasis en que Jacaerys era un bastardo y que se no podía permitir que un bastardo se sentara en el Trono de Hierro.

El príncipe Jacaerys tenía quince años al comienzo de la guerra civil. Su dragón, Vermax, estaba prosperando y crecía cada año. En el primer consejo de la reina Rhaenyra en Rocadragón, Jacaerys y Lucerys se ofrecieron como mensajeros para visitar a los señores de Poniente recabando apoyo para su reclamo. Rhaenyra lo permitió, a pesar de su juventud, pero antes de consentir les hizo jurar sobre una copia de La estrella de siete puntas que no tomarían parte en ninguna batalla. Al día siguiente, en la coronación de Rhaenyra como Reina de los Ándalos, los Rhoynar y los Primeros Hombres, Jacaerys fue nombrado Príncipe de Rocadragón.

Jacaerys, como hijo mayor de Rhaenyra, recibió la misión más difícil como mensajero. Montó su dragón Vermax y visitó a Lady Jeyne Arryn en el Nido de Águilas, Lord Borrell y Lord Sunderland en Villahermana, Lord Desmond Manderly en Puerto Blanco y Lord Cregan Stark en Invernalia. El príncipe era tan encantador y su dragón tan temible, que cada uno de los señores que visitó prometió apoyo para el reclamo de su madre Rhaenyra. Jacaerys ganó El Norte a través del Pacto de Hielo y Fuego, prometiendo al joven Cregan una princesa Targaryen como novia. Hongo, en su relato sobre la guerra, afirmó que Vermax puso una nidada de huevos en las criptas debajo de Invernalia. Hongo también afirma que Jacaerys se enamoró de la media hermana bastarda de Lord Cregan, Sara Nieve, y se casó con ella en secreto, aunque el archimaestre Gyldayn lo descarta y llega a cuestionar la existencia de dicha bastarda. </p>

<h3>Criston Cole</h3>
<img className="img1" src="https://www.desdelacuna.net/wp-content/uploads/2022/08/sir-criston-cole-la-casa-del-drago%CC%81n-1024x576.jpg" alt="" />
<p className="house2">Criston fue hijo de un mayordomo de Lord Dondarrion en Refugio Negro. Ganó un combate cuerpo a cuerpo en un torneo celebrado en Poza de la Doncella para celebrar la ascensión del rey Viserys I Targaryen, llamando la atención de la corte real al lograr desarmar de Hermana Oscura al príncipe Daemon Targaryen con su lucero del alba. Él le entregó la laurea a la princesa Rhaenyra Targaryen, cuyo favor usó al desmontar a Daemon en la justa, así como los gemelos Cargyll de la Guardia Real, antes de ser desmontado por Lord Lymond Mallister. A partir de entonces, el rey Viserys nombró a Criston el escudo juramentado personal de la princesa Rhaenyra. En 105 d.C., el joven de 23 años de edad se convirtió en miembro de la Guardia Real, tomando el lugar del legendario Ser Ryam Redwyne.

En 111 d.C., un gran torneo se ofreció en Desembarco del Rey para celebrar el quinto aniversario del matrimonio entre el rey Viserys I y la reina Alicent Hightower. Durante el torneo, la princesa Rhaenyra tuvo como paladín a Ser Criston Cole quien, llevando su prenda, desmontó a varios campeones de la reina Alicent, incluyendo a dos de sus primos y a su hermano menor, Ser Gwayne Hightower.

Para 112 d.C., Ser Criston seguía siendo el campeón de Rhaenyra y su compañero constante. El Lord Comandante Ser Harrold Westerling murió en ese año y Criston fue nombrado su sucesor para liderar a las Capas Blancas.

Para 113 d.C., se rumoreaba que Cole tenía un romance con Rhaenyra. El septón Eustace afirmó que Ser Criston había ido al dormitorio de Rhaenyra a confesar su amor, ofreciendo fugarse con ella a una de las Ciudades Libres, donde comprometería su espada a un príncipe comerciante, pero que Rhaenyra se había negado diciendo que una Targaryen estaba destinada a ser más que la esposa de un mercenario y que si él podía olvidar sus votos a la Guardia Real, bien podía eventualmente olvidarse de sus votos matrimoniales. Sin embargo, Hongo, el bufón real, cuenta una historia diferente, afirmando que Rhaenyra había estado aprendiendo de seducción con su tío, el príncipe Daemon Targaryen, para perder su virginidad con Criston, el hombre al que amaba, en lugar de hacerlo con su prometido, su primo Laenor Velaryon. No obstante, el bufón afirmaba que la princesa no logró seducir a Ser Criston en la Torre de la Espada Blanca y que, despechada, se hizo consolar por Ser Harwin Strong. Cualquiera haya sido la verdad, Cole pasó de ser su más acérrimo defensor a su mayor enemigo y Rhaenyra pronto partió a Marcaderiva con Ser Harwin como su nuevo escudo juramentado.

En 114 d.C., Ser Criston asistió a la boda de Rhaenyra y Laenor, que incluyó siete días de banquete y de justas. Cole luchó con la prenda de la reina Alicent y durante una refriega dejó a Ser Harwin con la clavícula y el codo rotos. El lucero del alba de Criston también rompió el yelmo de Ser Joffrey Lonmouth, el favorito de Laenor, que murió a consecuencia del golpe seis días después. Luego de esto, Cole se convirtió en un firme defensor de la reina Alicent, llegando incluso a ser maestro de armas del príncipe Aemond Targaryen.Cuando el rey Viserys I Targaryen murió en el 129 d.C., Ser Criston y la reina Alicent Hightower reunieron al Consejo Privado para discutir la sucesión, manteniendo la muerte del rey en secreto. Criston se opuso a que Rhaenyra Targaryen, la Princesa de Rocadragón, o su esposo, el príncipe Daemon Targaryen, obtuvieran el poder, insistiendo en el rumor de que los hijos de Rhaenyra con Ser Laenor Velaryon eran bastardos. En lugar de Rhaenyra, los Verdes pretendían coronar a su medio hermano menor, el príncipe Aegon el Mayor. Según el septón Eustace, Ser Criston degolló a Lord Lyman Beesbury, el único consejero que apoyó a Rhaenyra, mientras que Hongo afirmó que Criston en cambio lo arrojó por una ventana. No obstante, ninguno de los dos cronistas estuvieron presentes en la reunión.

Ser Criston detuvo a los partidarios de los Negros que permanecieron en la corte. Cuando Criston se presentó ante el príncipe Aegon para convencerle de tomar el Trono de Hierro, Hongo narra que el Guardia Real lo encontró con una joven del Lecho de Pulgas, mientras que Eustace afirmó que Aegon estaba en una situación más respetable con la hija de un mercader. Según el septón, Ser Criston le dijo al príncipe que él y sus hermanos serían asesinados por Rhaenyra si no reclamaba el trono.

Durante la coronación de Aegon en Pozo Dragón, Criston colocó la corona de Aegon el Conquistador sobre la cabeza del joven rey. Criston fue conocido como el Hacedor de Reyes debido a su apoyo a Aegon II.

Tras estallar la Danza de los Dragones y sucederse sus batallas, Aegon II se vio frustrado con su Mano del Rey, Ser Otto Hightower, y concedió el cargo a Ser Criston Cole. Las fuerzas del Hacedor de Reyes rápidamente tomaron Valle Oscuro y Reposo del Grajo.
</p>




        </div>
    )
}
export default Personajes